version: '2.1'

services:
  discovery-server:
    image: discovery-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

#  mongodb:
#    image: mongo:latest
#    #environment:
#      #MONGO_INITDB_DATABASE: movie
#      #MONGO_INITDB_ROOT_USERNAME: root
#      #MONGO_INITDB_ROOT_PASSWORD: rootpassword
#    ports:
#      - 27017:27017
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./mongo-volume:/data/db
#    #command: mongod --auth
#
#
#  mongodb-service:
#    image: mongodatabase-service
#    build:
#      context: ../mongoDataBaseMovie-service
#      dockerfile: Dockerfile
#    ports:
#      - "8087:8087"
#    links:
#      - discovery-server
#    depends_on:
#      - mongodb
#      - discovery-server
#
#
#  splitMovie-service:
#    image: splitmovie-service
#    build:
#      context: ../movie-splitMovie-service
#      dockerfile: Dockerfile
#    ports:
#      - "8084:8084"
#    links:
#      - discovery-server
#    volumes:
#      - ../discovery-server/videos:/home/user/videos
#    depends_on:
#      - discovery-server

  postgres:
    image: postgres
    #network_mode: bridge
    container_name: postgres_container
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ../movie-dataBase/src/main/resources/sql/dataStorage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=comments
      - dbhost=localhost
    networks:
      - code-network


#  dataBaseMovie-service:
#    image: data-base-movie-service
#    build:
#      context: ../movie-dataBase
#      dockerfile: Dockerfile
#    ports:
#      - "8086:8086"
#    volumes:
#      - /src/main/resources/sql/postgres:/home/user/sql/postgres
#    depends_on:
#      - postgres

  movie-commentary-service:
    image: movie-commentary-service
    build:
      context: ../movie-commentary-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - /src/main/resources/sql/postgres:/home/user/sql/postgres/comments
    depends_on:
      - postgres

networks:
  code-network:
    driver: bridge
volumes:
  pgdata:
    external: true