
spring:
  application:
    name: movie-MongoDataBase-server
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie

server:
  port: 8088

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#   serviceUrl.defaultZone: http://discovery-server:8761/eureka/
    #serviceUrl.defaultZone: http://localhost:8761/eureka
