
spring:
  application:
    name: movie-MongoDataBase-server
server:
  port: 8087

dockerspring:
  data:
    mongodb:
      #authentication-database: admin
      #username: root
      #password: rootpassword
      uri: mongodb://localhost:27017/test

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://eureka-service:8761/eureka/
    #serviceUrl.defaultZone: http://localhost:8761/eureka
