
spring:
  application:
    name: movie-MongoDataBase-server
server:
  port: 8087

dockerspring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: test
      port: 27017
      host: localhost

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://eureka-service:8761/eureka

#spring:
#  data:
#  mongodbhost=localhost
#    spring.data.mongodb.port=27017
#    spring.data.mongodb.repositories.enabled=true # if spring data repository support is enabled
