
spring:
  application:
    name: movie-MongoDataBase-server
server:
  port: 8088

dockerspring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      uri: mongodb://localhost:27017/movie

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#   serviceUrl.defaultZone: http://discovery-server:8761/eureka/
    #serviceUrl.defaultZone: http://localhost:8761/eureka
