spring:
  application:
    name: eureka-service
server:
    port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://discovery-server:${server.port}/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file: discoverService.log