spring:
  application:
    name : ratings-splitMovie-service
  profiles:
      active: default
server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://eureka-service:8761/eureka
    #serviceUrl.defaultZone: http://localhost:8761/eureka
