spring:
  application:
    name : splitMovie-service
  profiles:
      active: default
server:
  port: 8084

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file: splitMovieService.log

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl.defaultZone: http://discovery-server:8761/eureka
#    serviceUrl.defaultZone: http://localhost:8761/eureka
