CREATE TABLE IF NOT EXISTS COMMENTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    content VARCHAR(500) NOT NULL,
    id_user INTEGER NOT NULL,
    id_movie INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS MOVIES (
    id INTEGER NOT NULL,
    PRIMARY KEY(id)
);

