DELETE FROM COMMENTS;
DELETE FROM USERS;
DELETE FROM MOVIES;

ALTER TABLE COMMENTS
ADD CONSTRAINT fk_id_user
FOREIGN KEY (id_user) REFERENCES users(id);

ALTER TABLE COMMENTS
ADD CONSTRAINT fk_id_movie
FOREIGN KEY (id_movie) REFERENCES MOVIES(id);
