DROP TABLE comments CASCADE;

CREATE TABLE IF NOT EXISTS COMMENTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    content VARCHAR(500) NOT NULL,
    id_user INTEGER NOT NULL,
    id_movie VARCHAR(64) NOT NULL,
    PRIMARY KEY(id)
);